
[env:esp32dev]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

upload_protocol = esptool
upload_port = /dev/cu.usbmodem1101

monitor_speed = 115200
upload_speed = 115200

build_flags =
  -Wall
  -Wextra

lib_deps =
    Serial
    Wire
    adafruit/Adafruit NeoPixel@^1.12.0
